### ISSUE TITLE
Please change all instances of "Address__c" in data/properties-data.json to "Street_Address__c" 

### ISSUE THREAD

**Issue by burakqa** [trailheadapps/dreamhouse-lwc#237]
I downloaded the dreamhouse app and when I executed  the following command on VS Code  to import data 

    sfdx force:data:tree:import -p ./data/sample-data-plan.json

I got an error for each address  stating

errors":[{"statusCode":"REQUIRED_FIELD_MISSING","message":"Required fields are missing: [Street_Address__c]","fields":["Street_Address__c"]}]}

When I changed every instance of "Address__c" in data/properties-data.json  to "Street_Address__c" , the problem went away and I was able to import the data just fine.

**Comment by albarivas** [comment]
Hi, thanks for informing us about your issue. As you can see [here](https://github.com/trailheadapps/dreamhouse-lwc/blob/master/force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml), the name of the field
 is Address__c. You must have done a replacement or something similar in the field before deploying it. Deploy works like a charm for me, please do a fresh clone and try to deploy again.
