### ISSUE TITLE
Permission Set "Walkthroughs" is not there

### ISSUE THREAD

**Issue by nikhil317rao** [trailheadapps/dreamhouse-lwc#288]
### Summary

Hey everyone, in the instructions for the app, it gives instructions to optionally install a permission set "Walkthroughs." However, in the permissionsets folder, no such permission set exists; only a "dreamhouse" permission set. So probably want to either add the permission set XML file to the folder, or remove that from the instructions. You get an error when trying to do a push when referencing the missing permission set.

**Comment by albarivas** [comment]
Hi @nikhil317rao, the Walkthroughs permission set gets auto-created with In-App guidance activation. There's a note on the README about that.
Thanks for reaching out!
