### ISSUE TITLE
Husky pre-commit hook is not compatible with Windows

### ISSUE THREAD

**Issue by pozil** [trailheadapps/dreamhouse-lwc#309]
The Husky pre-commit hook that runs formatting, linting and tests uses shell commands that are not compatible with Windows. These are only working in *nix environments.

Problematic code in `package.json`:
```
"precommit": "npm run prettier:verify && [ $? -eq 0 ] && (npm run lint && npm run test) || exit -1"
```

This issue affects all sample apps.

**Comment by albarivas** [comment]
Fixed in https://github.com/trailheadapps/dreamhouse-lwc/pull/311
