### ISSUE TITLE
Auth command in readme should be force:auth:... not auth:

### ISSUE THREAD

**Issue by owenschoppe** [trailheadapps/dreamhouse-lwc#337]
### Summary

I think the readme needs to be updated to reflect the latest sfdx cli commands.

### Steps To Reproduce:

1.  Try using the setup steps

### Expected result

I should have been able to auth into my dev hub org.

### Actual result

Got the warning:
```
 ›   Warning: auth:web:login is not a sfdx command.
Did you mean force:auth:web:login? [y/n]: 
```

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by pozil** [comment]
Hi @owenschoppe, the correct command is indeed `sfdx auth:web:login` as [documented here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_web.htm#cli_reference_auth_web_login). The extra `force` prefix was dropped from the Salesforce CLI more than a year ago.
Please make sure to use an up to date version. For reference, the current CLI version is `7.117.0` and here are the [update instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm).
